export 'package:flutter/material.dart';
export 'package:json_parsing/controller/albums_controller.dart';
export 'package:json_parsing/controller/photos_controller.dart';
export 'package:json_parsing/controller/posts_controller.dart';
export 'package:json_parsing/helper/data_helper.dart';
export 'package:json_parsing/screens/home/homescreen.dart';
export 'package:json_parsing/screens/views/albums_screen.dart';
export 'package:json_parsing/screens/views/atodos_screen.dart';
export 'package:json_parsing/screens/views/comments_screen.dart';
export 'package:json_parsing/screens/views/photos_screen.dart';
export 'package:json_parsing/screens/views/posts_screen.dart';
export 'package:json_parsing/screens/views/users_screen.dart';
export 'package:json_parsing/utils/globals/globals.dart';
export 'package:json_parsing/utils/routes/app_routes.dart';
export 'package:provider/provider.dart';

export 'controller/atodos_controller.dart';
export 'controller/comments_controller.dart';
export 'controller/users_controller.dart';
